[package]
name = "mini-redis-tmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
mini-redis = "0.4.1"
tokio = { version = "1.18.2", features = ["full"] }
